### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rngtng** [rngtng/httpyac-plugin-meta-exports#1]
* [ ] don't fail on fail
* [ ] figure out via global vars get erased!?
* [ ] better syntax
* [ ] multiple var support
